#Deploys with the RDS not the local psql
---
- hosts: all
  become_method: sudo
  become: yes
  gather_facts: False


  vars:
    ssh_key: "{{ home }}/.ssh/id_rsa"
    user: ubuntu
    home: "/home/{{ user }}"
    venv_home: "{{ home }}/.virtualenvs"
    venv_bin: "{{ home }}/.virtualenvs/{{ project_name }}/bin"
    project_name: "django_session"
    project_root: "{{ home }}/{{ project_name }}"
    django_settings: "{{ 'config.settings.production' }}"
    local_project_root: "{{ playbook_dir | dirname }}"
    local_ssh_key: /home/kumaraswins/.ssh/id_rsa
    server_name: "{{ hostvars[inventory_hostname]['ansible_host'] }}"


  tasks:

    - debug:
        msg: "{{ server_name }}"

    - name: get variables
      debug: var=hostvars


    - name: rsync project to target host
      synchronize:
        src: "{{ local_project_root }}"
        dest: "{{ home }}"
        rsync_opts:
          - "--delete"
      

    - name: restart gunicorn
      service: name=mgunicorn state=restarted
